### ISSUE TITLE
Чисто структурная поправка

### ISSUE THREAD

**Issue by YawKar** [RandomName-proj/Spring-Homework#1]
https://github.com/RandomName-proj/Spring-Homework/blob/27e0b48a305e6909db0d6cdb93cca5f09d1e34a8/homework-1/src/main/java/com/example/demo/DemoApplication.java#L9-L33

Сначала в принципе про домашку: всё сделал чётко, лаконично, закинул все ручки в `DemoApplication`

Есть момент, который я не говорил в ТЗ домашки: надо выносить контроллеры в отдельные классы. То есть вот у тебя есть главный класс приложения `DemoApplication`, в нём практически всегда во всех Spring Boot приложениях должен оставаться только метод `main(...)` и кучка аннотаций над самим классом (например, `@EnableЧто-нибудьТипаКомпонентСкана`, то есть всякие аннотации для настройки самого SpringBootApplication).

Так вот, а у тебя там прям в этом классе объявляются ручки и этот класс объявляется как компонент `@RestController`, что вводит небольшую сумятицу, так как класс `DemoApplication` обычно используется как java-code конфигурация, а тут ещё и роль контроллера на себя берёт.

Что нужно сделать: 
- создать пакет `com.example.demo.controller`
- создать в нём класс `com.example.demo.controller.HelloController`
- перенести из `com.example.demo.DemoApplication` весь функционал ручек в `com.example.demo.controller.HelloController`

В результате класс `DemoApplication` должен будет остаться только с одной аннотацией `@SpringBootApplication` и с одним методом `p s v main(...)`, а `HelloController` будет инкапсулировать в себе всю логику обработки запросов

**Comment by YawKar** [comment]
https://github.com/RandomName-proj/Spring-Homework/blob/27e0b48a305e6909db0d6cdb93cca5f09d1e34a8/homework-1/src/main/java/com/example/demo/DemoApplication.java#L27-L31

Так как ты используешь `@RestController`, а не `@Controller`, то у тебя нет необходимости писать `@ResponseBody` над методом, потому что REST контроллеры по умолчанию записывают в response body то, что выплёвывает твой метод-обработчик

**Comment by YawKar** [comment]
https://github.com/RandomName-proj/Spring-Homework/blob/27e0b48a305e6909db0d6cdb93cca5f09d1e34a8/homework-1/src/main/java/com/example/demo/DemoApplication.java#L22-L25

У `@PathVariable` можно не писать в скобках название переменной пути, если оно совпадает с названием параметра метода (как у тебя в данном случае `String name` имеет то же имя, что и параметр в url `{name}`)

**Comment by RandomName-proj** [comment]
Сделал в коммите https://github.com/RandomName-proj/Spring-Homework/commit/f8741e3f53982e1680a536b4576023fe14a73c07

**Comment by YawKar** [comment]
Всё выполнил, молодец!
